### ISSUE TITLE
shipit_static_analysis: Close issues that have been fixed.

### ISSUE THREAD

**Issue by tomprince** [mozilla-releng/services#1190]
**MozReview URL:** https://reviewboard.mozilla.org/r/245838/#review253028

**Problem:** The bot should close detected issues in subsequent runs, when it detects they have been fixed. This is related but not identical to #663 and #957.

**Comment by jankeromnes** [comment]
Hi @tomprince, thank you for this suggestion! To ensure that we completely understand your request, do you mean that:

STR:
- Developer pushes a commit to MozReview
- Review Bot detects a defect in the commit, and opens a MozReview issue
- Developer fixes that issue, and pushes a new revised commit to MozReview

Expected:
- MozReview and/or Review Bot should automatically close the issue, because it was fixed

Actual behavior:
- The MozReview issue remains open, and has to be manually closed by the developer or the reviewer

**Comment by tomprince** [comment]
Yes, exactly.

**Comment by La0** [comment]
@jankeromnes We could indeed close the issue:
* if no issue is detected on the patch
* a previous automated review was opened (that would need some tweaks in the comment detection)

**Comment by La0** [comment]
That would be automatically done if we used Phabricator lint/unit results.

Any thoughts @marco-c ?

**Comment by marco-c** [comment]
#1991 would partially help, as after that we'd use lint results for most checkers. We'd still have a few ignorable issues though (for which we don't want to use lint results).

For ignorable issues, we could close all issues that were detected in the previous run of the bot (using the index to find the previous run of the bot) and which are no longer detected.
To fix #663, we could publish only issues that are detected now and were not detected in the previous run of the bot.
